language: node_js
before_script:
  - psql -c 'create database "userific-test";' -U postgres
  - psql -d userific-test -f node_modules/userific-postgres/share/users.sql
services:
    mongodb
node_js:
    - "0.8"
    - "0.10"
