HOST: http://www.google.com/

--- Userific-Server ---

---
Welcome to the documentation for the Userific Server project. Userific provides an way to manage users in your application via a rest api. Userific supports several different backends. No matter which backend is used, the RESTful api is the same for the server
---

--
User Resources
The following is a section of resources related to user management
--

Register a new user account
POST /register
> Content-Type: application/json
{ "email":"foo@example.com", "password": "barPassword" }
< 201
< Content-Type: application/json
{ "_id": "fooUserID", "email": "foo@example.com" }
+++++
< 409
< Content-Type: application/json; charset=utf-8
{"code": "MissingParameter", "message": "Register failed", "errors": [ { "param": "email", "msg": "required" }]}
+++++
< 409
< Content-Type: application/json; charset=utf-8
{"code": "MissingParameter", "message": "Register failed", "errors": [ { "param": "password", "msg": "password must be at least 4 characters long" }]}



Authenticate an existing user account
POST /authenticate
> Content-Type: application/json
{ "email":"foo@example.com", "password": "barPassword" }
< 200
< Content-Type: application/json
{ "_id": "fooUserID", "email": "foo@example.com" }
+++++
< 401
< Content-Type: application/json; charset=utf-8
{"code":"InvalidCredentials","message":"user not found"}
+++++
< 409
< Content-Type: application/json; charset=utf-8
{"code": "MissingParameter", "message": "Authenticate failed", "errors": [ { "param": "email", "msg": "required" }]}
+++++
< 409
< Content-Type: application/json; charset=utf-8
{"code": "MissingParameter", "message": "Authenticate failed", "errors": [ { "param": "password", "msg": "required" }]}

