HOST: http://www.google.com/

--- Userific-Server ---

---
Welcome to the documentation for the Userific Server project. Userific provides an way to manage users in your application via a rest api. Userific supports several different backends. No matter which backend is used, the RESTful api is the same for the server
---

--
User Resources
The following is a section of resources related to user management
--

Save new products in your shopping cart
POST /register
> Content-Type: application/json
{ "email":"foo@example.com", "password": "barPassword" }
< 201
< Content-Type: application/json
{ "_id": "fooUserID", "email": "foo@example.com" }
+++++
< 401
< Content-Type: application/json; charset=utf-8
{"message":"You have not provided proper request token"}
+++++
< 403
< Content-Type: application/json; charset=utf-8
< X-Rate-Limit-Remaining: 0
{"message":"Too many requests, please try again later (see X-Rate-Limit-Remaining header)"}
+++++
< 418
{"message":"Teapot, seriously?"}
+++++
< 451
<message>Legally restricted, sorry</message>


-- Payment Resources --

This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }
